name: Github Actions Demo

on:
  schedule:
    - cron: '15 6 * * 6'

  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      
  pull_request:
    branches:
      - 'main'
  
  workflow_dispatch:
  
